#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoonTimeApp.Resource", IsApplication=true)]

namespace MoonTimeApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blank = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int firstquarter90highsky = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int firstquarter90ineast = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int firstquarter90inwest = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int firstquarter90loweast = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int firstquarter90lowsky = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int firstquarter90lowwest = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int firstquarter90rising = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int firstquarter90setting = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int fullmoon180highsky = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fullmoon180ineast = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int fullmoon180inwest = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int fullmoon180loweast = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fullmoon180lowsky = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int fullmoon180lowwest = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int fullmoon180rising = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fullmoon180setting = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_launcher = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int newmoon0highsky = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int newmoon0ineast = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int newmoon0inwest = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int newmoon0loweast = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int newmoon0lowsky = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int newmoon0lowwest = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int newmoon0rising = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int newmoon0setting = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int thirdquarter90highsky = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int thirdquarter90ineast = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int thirdquarter90inwest = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int thirdquarter90loweast = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int thirdquarter90lowsky = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int thirdquarter90lowwest = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int thirdquarter90rising = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int thirdquarter90setting = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int wanningcrest45highsky = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int wanningcrest45ineast = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int wanningcrest45inwest = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int wanningcrest45loweast = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int wanningcrest45lowsky = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int wanningcrest45lowwest = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int wanningcrest45rising = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int wanningcrest45setting = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int wanninggibbous135highsky = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int wanninggibbous135ineast = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int wanninggibbous135inwest = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int wanninggibbous135loweast = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int wanninggibbous135lowsky = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int wanninggibbous135lowwest = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int wanninggibbous135rising = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int wanninggibbous135setting = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int waxingcrest45highsky = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int waxingcrest45ineast = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int waxingcrest45inwest = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int waxingcrest45loweast = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int waxingcrest45lowsky = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int waxingcrest45lowwest = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int waxingcrest45rising = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int waxingcrest45setting = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int waxinggibbous135highsky = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int waxinggibbous135ineast = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int waxinggibbous135inwest = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int waxinggibbous135loweast = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int waxinggibbous135lowsky = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int waxinggibbous135lowwest = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int waxinggibbous135rising = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int waxinggibbous135setting = 2130837570;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int btnCalcResults = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int btnExit1 = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int btnExit2 = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int editAppearance = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int mainProgramButton = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int numberPickerElong = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int pic = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int radioBtnDirection = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int radioButtonEast = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int radioButtonFullMoon = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int radioButtonNewMoon = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int radioButtonWest = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView3 = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int videoView1 = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int App = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int android = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int MoonTimeApp = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int btnCalcResults = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
